name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: run multiple echo
        run: |
          echo "Hello, Faizan!🎉"
          echo "Hello, Furqan"
