name: Hello World Workflow

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "This is build Stage"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "This is TEST Stage"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "This is Deploy Stage"
